In [5]:
#import ast,sys
#input_str = sys.stdin.read()
#input_list = ast.literal_eval(input_str)
list_1 = [1,2,3]
list_2 = [4,5,6]
list_3 = [7,8,9]

import numpy as np
array_1 = np.array([list_1, list_2, list_3])

print(array_1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [10]:
import numpy as np

list_1 = [2,3,4,5]
list_2 = [7,8,9,6]
ar1 = np.array(list_1)
ar2 = np.array(list_2)

ar3  =ar1*ar2
list_3 = list(ar3)

print(list_3)
print(type(list_3))


[14, 24, 36, 30]
<class 'list'>


In [28]:
import numpy as np

list_1 = [10,11,12,13]
list_2 = [15,12,13,14] 

ar1 = np.array(list_1)
ar2 = np.array(list_2)
ar3 = ar1*ar2


print(ar3.ndim)
print(ar3.itemsize)
print(ar3.shape)
print(ar3.dtype)


1
4
(4,)
int32


In [36]:
ar_hstack = np.hstack((ar2, ar1))
print(ar_hstack)

ar_vstack = np.vstack((ar_hstack, [1,2,3,4,5,6,7,8]))
print(ar_vstack)


[15 12 13 14 10 11 12 13]
[[15 12 13 14 10 11 12 13]
 [ 1  2  3  4  5  6  7  8]]


In [40]:
ar = [[1,2,3,4],[4,7,5,6],[9,0,7,8],[6,7,8,5]]
print(ar)
VFunc = np.vectorize(lambda x : x/5)
VFunc(ar)



[[1, 2, 3, 4], [4, 7, 5, 6], [9, 0, 7, 8], [6, 7, 8, 5]]


array([[0.2, 0.4, 0.6, 0.8],
       [0.8, 1.4, 1. , 1.2],
       [1.8, 0. , 1.4, 1.6],
       [1.2, 1.4, 1.6, 1. ]])

In [46]:
print(np.linalg.eig(ar),"\n")
print(np.linalg.det(ar),"\n")
print(np.linalg.inv(ar))



(array([20.65349084+0.j        ,  4.10810319+0.j        ,
       -2.38079701+0.62433339j, -2.38079701-0.62433339j]), array([[ 0.25852583+0.j        ,  0.04794751+0.j        ,
         0.66164849+0.j        ,  0.66164849-0.j        ],
       [ 0.53554697+0.j        ,  0.70876597+0.j        ,
         0.13348103-0.05654153j,  0.13348103+0.05654153j],
       [ 0.52644157+0.j        , -0.67741786+0.j        ,
        -0.21531945-0.35103431j, -0.21531945+0.35103431j],
       [ 0.60762909+0.j        ,  0.19093686+0.j        ,
        -0.46447574+0.39481881j, -0.46447574-0.39481881j]])) 

513.9999999999998 

[[-0.42217899  0.16731518  0.11478599 -0.04669261]
 [-0.1536965   0.19455253 -0.06420233 -0.0077821 ]
 [ 0.34046693 -0.39299611 -0.06031128  0.29571984]
 [ 0.1770428   0.15564202  0.04863813 -0.20622568]]
